# By convention, toolchain_type targets are named "toolchain_type" and
# distinguished by their package path. So the full path for this would be
# //rules/zip:toolchain_type.
toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)
