# load("@aspect_rules_py//py:defs.bzl", "py_binary")
# load("@pip//:requirements.bzl", "requirement")
load("//rules/python:defs.bzl", "py_binary")

py_binary(
    name = "main",
    srcs = ["main.py"],
    # deps = [requirement("requests")],
)
